-- 학생별 포털 지정과목 원본과 최신 스냅샷 버전을 저장한다.
ALTER TABLE public.students
    ADD COLUMN designated_courses_snapshot_version TIMESTAMP WITH TIME ZONE NULL;

CREATE TABLE public.student_designated_courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    student_id UUID NOT NULL,
    source_order INTEGER NOT NULL,
    org_cls_cd VARCHAR(255) NULL,
    subjt_cd VARCHAR(255) NULL,
    subjt_nm VARCHAR(255) NULL,
    point INTEGER NULL,
    precp_resn_cd VARCHAR(255) NULL,
    cret_gain_year INTEGER NULL,
    cret_smr_nm VARCHAR(255) NULL,
    sno VARCHAR(255) NULL,
    CONSTRAINT pk_student_designated_courses PRIMARY KEY (id),
    CONSTRAINT uk_student_designated_courses_student_order
        UNIQUE (student_id, source_order),
    CONSTRAINT fk_student_designated_courses_student_id
        FOREIGN KEY (student_id) REFERENCES public.students (student_id) ON DELETE CASCADE
);
